name: Build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v2
      - name: Lint
        run: yarn lint
      - name: Check styling
        run: yarn prettier --check .
      - name: Type check
        run: yarn tsc --noEmit
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-yarn@v2
      - name: Install Playwright deps
        run: yarn playwright install chromium
      - name: Test
        run: yarn test
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: test-results
  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: mskelton/setup-yarn@v2
      - name: Build
        run: yarn build
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
